# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_view = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_view.sizePolicy().hasHeightForWidth())
        self.img_view.setSizePolicy(sizePolicy)
        self.img_view.setMinimumSize(QtCore.QSize(0, 0))
        self.img_view.setObjectName("img_view")
        self.horizontalLayout_2.addWidget(self.img_view)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_threshold = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_threshold.setMaximum(1.0)
        self.spinBox_threshold.setSingleStep(0.01)
        self.spinBox_threshold.setProperty("value", 0.1)
        self.spinBox_threshold.setObjectName("spinBox_threshold")
        self.horizontalLayout_5.addWidget(self.spinBox_threshold)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setWhatsThis("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_min_sigma = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_min_sigma.setWhatsThis("")
        self.spinBox_min_sigma.setPrefix("")
        self.spinBox_min_sigma.setMaximum(500.0)
        self.spinBox_min_sigma.setSingleStep(0.5)
        self.spinBox_min_sigma.setProperty("value", 1.0)
        self.spinBox_min_sigma.setObjectName("spinBox_min_sigma")
        self.horizontalLayout.addWidget(self.spinBox_min_sigma)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_max_sigma = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_max_sigma.setMinimum(0.1)
        self.spinBox_max_sigma.setMaximum(1000.0)
        self.spinBox_max_sigma.setSingleStep(0.5)
        self.spinBox_max_sigma.setProperty("value", 5.0)
        self.spinBox_max_sigma.setObjectName("spinBox_max_sigma")
        self.horizontalLayout_3.addWidget(self.spinBox_max_sigma)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_num_sigma = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_num_sigma.setProperty("value", 10)
        self.spinBox_num_sigma.setObjectName("spinBox_num_sigma")
        self.horizontalLayout_4.addWidget(self.spinBox_num_sigma)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinBox_overlap = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_overlap.setMaximum(1.0)
        self.spinBox_overlap.setSingleStep(0.1)
        self.spinBox_overlap.setObjectName("spinBox_overlap")
        self.horizontalLayout_6.addWidget(self.spinBox_overlap)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_exclude_border = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_exclude_border.setMaximum(1000)
        self.spinBox_exclude_border.setObjectName("spinBox_exclude_border")
        self.horizontalLayout_8.addWidget(self.spinBox_exclude_border)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.spinBox_box_size = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_box_size.setMinimum(1.0)
        self.spinBox_box_size.setMaximum(1000.0)
        self.spinBox_box_size.setProperty("value", 5.0)
        self.spinBox_box_size.setObjectName("spinBox_box_size")
        self.horizontalLayout_11.addWidget(self.spinBox_box_size)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_calc_roi = QtWidgets.QPushButton(self.centralwidget)
        self.button_calc_roi.setObjectName("button_calc_roi")
        self.verticalLayout_3.addWidget(self.button_calc_roi)
        self.button_calc_centroids = QtWidgets.QPushButton(self.centralwidget)
        self.button_calc_centroids.setObjectName("button_calc_centroids")
        self.verticalLayout_3.addWidget(self.button_calc_centroids)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_prev = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_prev.setFont(font)
        self.button_prev.setObjectName("button_prev")
        self.verticalLayout_2.addWidget(self.button_prev)
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_next.setFont(font)
        self.button_next.setObjectName("button_next")
        self.verticalLayout_2.addWidget(self.button_next)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load_images = QtWidgets.QAction(MainWindow)
        self.action_load_images.setObjectName("action_load_images")
        self.action_load_annot = QtWidgets.QAction(MainWindow)
        self.action_load_annot.setObjectName("action_load_annot")
        self.action_load_masks = QtWidgets.QAction(MainWindow)
        self.action_load_masks.setObjectName("action_load_masks")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_toggle_side_menu = QtWidgets.QAction(MainWindow)
        self.action_toggle_side_menu.setCheckable(True)
        self.action_toggle_side_menu.setObjectName("action_toggle_side_menu")
        self.actionROI = QtWidgets.QAction(MainWindow)
        self.actionROI.setObjectName("actionROI")
        self.action_roi_settings = QtWidgets.QAction(MainWindow)
        self.action_roi_settings.setObjectName("action_roi_settings")
        self.menuFile.addAction(self.action_load_images)
        self.menuFile.addAction(self.action_load_annot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setStatusTip(_translate("MainWindow", "Reduce this to detect blobs with lower intensities."))
        self.label_4.setText(_translate("MainWindow", "Threshold"))
        self.spinBox_threshold.setStatusTip(_translate("MainWindow", "Reduce this to detect blobs with lower intensities."))
        self.label.setStatusTip(_translate("MainWindow", "the minimum standard deviation for Gaussian kernel. Keep this low to detect smaller blobs."))
        self.label.setText(_translate("MainWindow", "Min Sigma"))
        self.spinBox_min_sigma.setStatusTip(_translate("MainWindow", "the minimum standard deviation for Gaussian kernel. Keep this low to detect smaller blobs."))
        self.label_2.setStatusTip(_translate("MainWindow", "The maximum standard deviation for Gaussian kernel. Keep this high to detect larger blobs. "))
        self.label_2.setText(_translate("MainWindow", "Max Sigma"))
        self.spinBox_max_sigma.setStatusTip(_translate("MainWindow", "The maximum standard deviation for Gaussian kernel. Keep this high to detect larger blobs. "))
        self.label_3.setStatusTip(_translate("MainWindow", "The number of intermediate values of standard deviations to consider"))
        self.label_3.setText(_translate("MainWindow", "Num Sigma"))
        self.spinBox_num_sigma.setStatusTip(_translate("MainWindow", "The number of intermediate values of standard deviations to consider"))
        self.label_5.setStatusTip(_translate("MainWindow", "If the area of two blobs overlaps by a fraction greater than this, the smaller blob is eliminated."))
        self.label_5.setText(_translate("MainWindow", "Overlap"))
        self.spinBox_overlap.setStatusTip(_translate("MainWindow", "If the area of two blobs overlaps by a fraction greater than this, the smaller blob is eliminated."))
        self.label_7.setStatusTip(_translate("MainWindow", "Number of pixels to exclude from the border"))
        self.label_7.setText(_translate("MainWindow", "Exclude Border"))
        self.spinBox_exclude_border.setStatusTip(_translate("MainWindow", "Number of pixels to exclude from the border"))
        self.label_6.setText(_translate("MainWindow", "Box Period"))
        self.button_calc_roi.setText(_translate("MainWindow", "Calc ROI"))
        self.button_calc_centroids.setText(_translate("MainWindow", "Calc Centroids"))
        self.button_prev.setText(_translate("MainWindow", "Prev"))
        self.button_next.setText(_translate("MainWindow", "Next"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_load_images.setText(_translate("MainWindow", "Load Images"))
        self.action_load_images.setStatusTip(_translate("MainWindow", "Load Images. Navigate to a video or images folder"))
        self.action_load_annot.setText(_translate("MainWindow", "Load Annotations"))
        self.action_load_annot.setStatusTip(_translate("MainWindow", "Load annotations: bounding boxes, segmentation mask"))
        self.action_load_masks.setText(_translate("MainWindow", "Load Masks"))
        self.action_load_masks.setStatusTip(_translate("MainWindow", "Load segmentation masks"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setStatusTip(_translate("MainWindow", "Save annotations"))
        self.action_toggle_side_menu.setText(_translate("MainWindow", "Side Menu"))
        self.action_toggle_side_menu.setStatusTip(_translate("MainWindow", "Hide/Unhide class label side menu"))
        self.actionROI.setText(_translate("MainWindow", "ROI"))
        self.action_roi_settings.setText(_translate("MainWindow", "ROI"))

from pyqtgraph import GraphicsLayoutWidget
